### ISSUE TITLE
iPad Pro 12.9" for `V` [Digital Artist]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#37]
This is not for me/us, I already have a decent iPad 10.5" that serves my needs: https://github.com/dwyl/studio/issues/12#issuecomment-688843749
It's a **gift** for an up-and-coming Artist who wants to dive into https://procreate.art but lacks the funds. 

![image](https://user-images.githubusercontent.com/194400/166212172-c3037cfe-38ce-4706-8bd8-710e3c174fb4.png)

[![image](https://user-images.githubusercontent.com/194400/166212026-157d14f1-89d1-43be-96bc-080d2945435d.png)](https://youtu.be/Hi-CtwX3u0w)

![image](https://user-images.githubusercontent.com/194400/166211688-f3c7f611-1136-4e3f-ada7-dab425ce01d8.png)

Yes it's not new; it's "refurbished". It still has plenty of "life" left in it. 

Buying this _exact_ model from Apple today is **`£849`** (**€1,014`** at the time of writing)
[apple.com/uk/shop/product/FTFP2B/A/refurbished-129-inch-ipad-pro-wi-fi-512gb-2019-space-gray-3rd-generation](https://www.apple.com/uk/shop/product/FTFP2B/A/refurbished-129-inch-ipad-pro-wi-fi-512gb-2019-space-gray-3rd-generation?fnode=7c98ca236ca968d581f12fabc075b660e0523d99e6891d295258ba62f9bcdce958644ffc9b3c91a7574053714baf9ceec305cd4a901f5f85f51647313c7f981a756cf770f6effb69d9e425193c4b4e2d)

![image](https://user-images.githubusercontent.com/194400/166212633-25effee7-d53d-4814-a8d4-f7fe29a576e8.png)

So getting this on eBay (with the bank holiday discounts) isn't quite "half" the price ... but it's close. 
i.e. if we want to sell it on instead of give it away we can _easily_.

**Comment by nelsonic** [comment]
iPad buying YT blackhole ... 
![image](https://user-images.githubusercontent.com/194400/166224262-20f27ed7-7388-4e80-b547-3d1cd07ec89b.png)

Just watch this one:  Which iPad Should You Buy For Procreate? https://youtu.be/JYOIeObjfuo
[![image](https://user-images.githubusercontent.com/194400/166224352-bbf3ba5d-5701-4871-aa30-4202afe8015e.png)](https://youtu.be/JYOIeObjfuo)

Conclusion: the iPad Pro 12.9" (2018 3rd gen model) has the promotion display and plenty of power for procreate. 

Compared to the _base_ 2021 model which is **`£999`**:
https://www.apple.com/uk/shop/buy-ipad/ipad-pro/12.9-inch-display-128gb-space-grey-wifi
![image](https://user-images.githubusercontent.com/194400/166224696-e9ac0ea5-ec69-4d44-9244-3e28b42ee6f9.png)

The only benefit of the newer one would be the mini-LED display instead of  "liquid retina". 
If you have them side-by-side you _might_ be able to tell the difference ... 

[![image](https://user-images.githubusercontent.com/194400/166225015-19aacd0d-d393-4d1f-af4d-dd347b3fc951.png)](https://youtu.be/DAYwEhoGJDA)

But for the person we're buying _this_ iPad for who doesn't currently _have_ an iPad ...
And currently does all their sketching on an ancient Wacom Tablet connected to an equally antiquated Lenovo laptop ... 
This will feel like upgrading from a bicycle to a Tesla!

**Comment by nelsonic** [comment]
Just trying to decide if it's worth getting the **`1TB`** version for the added RAM (**`8GB`**): **`£522.24`**
![image](https://user-images.githubusercontent.com/194400/166329001-d110c0b0-16c8-432b-ae97-4a39edaacc86.png)

Or if the **`256GB`** version with (**`4GB`** of RAM) for **`£441.49`**
![image](https://user-images.githubusercontent.com/194400/166329183-e5639e11-9cd0-4b94-b3a7-57d55312b4b0.png)

It's an extra **`£80.75`** ... but could mean a decent amount more "longevity" and more layers in Procreate (or other graphics-intensive apps) ... 

Best iPads for Art in 2022: Why you DON'T have to buy new
[![image](https://user-images.githubusercontent.com/194400/166329697-a998a732-5a97-48ae-931e-658584548c3e.png)](https://youtu.be/lQIIZvdR2Fk)

**Comment by nelsonic** [comment]
If you want to understand this, watch this: https://youtu.be/lQIIZvdR2Fk?t=488 
[![image](https://user-images.githubusercontent.com/194400/166330647-afabf33a-ded0-4b6a-a329-be23058b1d80.png)](https://youtu.be/lQIIZvdR2Fk?t=488)

Basically, layers are a way of organising your designs/drawings in Procreate.
The more RAM your iPad has the more layers you can have which makes for more complex designs.
The iPad Pro 2018 with **`1TB`** has **`6GB`** of **RAM** can have **25** Layers vs. "only" 19 for the lower model. 💭 

Went with the "basic" one. The person in question will get every bit as much benefit out of it.
And it leaves us with the money to buy Apple Pencil ... ✏️  💸  🙄

**Comment by nelsonic** [comment]
Edit Photos in PROCREATE - Photo Manipulation Tutorial for beginners: https://youtu.be/x61BtRQIJbQ
[![image](https://user-images.githubusercontent.com/194400/166444461-9c68dace-d74b-4dbc-b31b-dae3f5296f44.png)](https://youtu.be/x61BtRQIJbQ)

this tutorial looks _siiiick_!! 
![image](https://user-images.githubusercontent.com/194400/166444767-3d32f44d-0843-47c2-9ead-59cba29b2e4a.png)

If I had infinite time, I would totally get sucked into this App!!

**Comment by nelsonic** [comment]
the person in question will be using the iPad Pro 12.9" for their digital art, 👨‍🎨 🎨 
but since they also do "wedding venue tours" for [@mosteirodelandim](https://github.com/mosteirodelandim), 👰‍♀️ 
they will be able to showcase the photos/videos of the venue + events in style. 😍 
we 100% consider this an investment that pays for itself. 📈 
but nobody is willing to pony-up the cash, so we have to. 👍

**Comment by nelsonic** [comment]
Clarity of purpose of the **`iPad Pro 12.9" 2020`** (version 4) for **`V`**

1. **_Practicing_ Digital Art** on-the-go and in their studio (doodling, concept art, story boarding, transforming photos, etc.)
2. **Photo Album for Landim** for tours etc -> store high resolution photos in an album on-device for in-person tours
3. **_Taking_ high quality photos** - the iPad Pro has a **_better_ camera** than their Android device - and 
  a. **_Editing_ photos** on-device for posting on Landim social.
  b. **_Posting_ photos** - both to the [**`new` website**](https://github.com/mosteirodelandim/landim-website) and [IG](https://github.com/dwyl/home/issues/29) 🙄 
  c. **_Managing_ social** - having a dedicated "work" device they can use to separate from their personal device.
4. **_Logging_ the updates** in the Landim CRM. [TBD] 🏦 

If they have time to create some custom digital art for [**`@home`**](https://github.com/dwyl/home/) that would be a mega bonus, but it's _not_ the focus. 🤞 

@iteles please LMK if this is clear before I share it with **`V`**. 🙏 [thanks!]

**Comment by iteles** [comment]
On this clarity of purpose:
1. **_Practicing_ Digital Art** 👌 
2. **Photo Album for Landim**  - Yes ***BUT*** this person is far from the only one who does tours and my eternal fight with everyone is to do this stuff on Google photos/drive where everyone can have access on their own devices. It is a good use for this person but they won't be _leaving_ the iPad in Landim so it won't be useful for all, just for them 👌 
3. **_Taking_ high quality photos** - 👌 
  a. **_Editing_ photos** 👌 
  b. **_Posting_ photos** - 👌 
  c. **_Managing_ social** - 👌 
4. **_Responding_ to enquiries** - I think this one we need to delete. The person who does the above will _not_ also be doing the responding to enquiries.
5. **_Logging_ the updates** in the Landim CRM. 👌 

https://github.com/mosteirodelandim/weddings/issues/2 - CRM issue

**Comment by nelsonic** [comment]
@iteles thanks for your quick response, 👌 
please **`edit`** my comment to remove any bullet points you feel are not relevant. 📝 
Thanks. 🙏

**Comment by nelsonic** [comment]
@iteles agree that if the enquiries go straight into a CRM inbox, then _anyone_ can respond to them. 👌 
Didn't know about https://github.com/mosteirodelandim/weddings/issues/2 because I'm not an org member ... 🤷‍♂️

**Comment by nelsonic** [comment]
For future reference, we ended up getting an **`iPad Pro 12.9" 2020`** (`v.4`) with **`256GB` Storage**  
it has **`LTE`**, so it can _optionally_ be used with a **`SIM`** card as a mobile office if needed.

**Comment by iteles** [comment]
@nelsonic Updated your response directly.


Also, I've sent you another invite for the org 👍 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/4185328/183465938-bffce457-d2b1-43a3-90c5-e12153147f8f.png">

**Comment by nelsonic** [comment]
@LuchoTurtle has **`V`** integrated the **`iPad Pro 12.9"`** into his workflow? 💭 
Has he managed to download the Landim photos+videos for doing visits?
(_can we close this issue?_)

**Comment by LuchoTurtle** [comment]
@nelsonic He hasn't just yet mainly because he's been speedrunning a painting for the family reunion on the 3rd. 
He had no clue he was supposed to download Landim photos for his visits, there appears to be a miscommunication. He's yet to do any visits since then so he really hasn't had the chance 🤷

**Comment by nelsonic** [comment]
I shared the list above https://github.com/dwyl/studio/issues/37#issuecomment-1208286674 with **`V`** before we gave him the iPad. Maybe need to re-share. 💭

**Comment by LuchoTurtle** [comment]
This should be closed, I wager 😁

**Comment by nelsonic** [comment]
Sadly, one of the original purposes for the iPad was not clearly communicated with the recipient (despite my best efforts) so there is no ***`offline`*** Landim Photo Album they can use for "visitas".

@LuchoTurtle are you able to help **`V`** with the photo album?

**Comment by LuchoTurtle** [comment]
I'll talk to him. He's been using the tablet much more for drawing and doodling but yes, I'll ask him if he already has the photos for the visits.

**Comment by nelsonic** [comment]
Any luck getting the album working on the iPad?

**Comment by LuchoTurtle** [comment]
He has it working and says he's used the tablet to show pictures, yes.

**Comment by nelsonic** [comment]
Awesome. Thanks for confirming @LuchoTurtle  👌
Closing. ✅
