### ISSUE TITLE
Research: Wireless Microphones

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#40]
@LuchoTurtle for the upcoming family meeting, we need to get a couple of wireless microphones. 
Can you help?

We have a Rode wireless Go (v1) which will work if the distance is 10m< ... 
But I think we should expect larger distances and we need _two_. 💭

**Comment by LuchoTurtle** [comment]
We should be fine when it comes to the distance. People speaking will be close to the speakers so I don't think we need two microphones, one should suffice.

However, I have some qualms about your Rode Wireless Go and if they work with a Partybox 100 speaker. It *should* work because the mic receiver can connect to ay phone type jack device (which is the case of the PB100). Still, we should give it a whirl before Sept 3rd.

If it doesn't work, any cabled microphone will work (even wireless ones - as long as they have an adapter that connects to the PB100) and it should be absolutely fine for the event. Even if we bring two PB100s, we can pair them with TWS and still only need to use one microphone.

![image](https://user-images.githubusercontent.com/17494745/185913157-af574003-0638-4a95-bb96-9f431153cd27.png)

**Comment by nelsonic** [comment]
https://www.estudiopt.pt/audio/microfones/mao/rode-interview-go-p-wireless-go/

**Comment by LuchoTurtle** [comment]
> https://www.estudiopt.pt/audio/microfones/mao/rode-interview-go-p-wireless-go/

I think buying this is unnecessary, we just gotta make sure the receiver can be plugged into the PB100. If it can, we can use what we already have and save costs :)

**Comment by nelsonic** [comment]
@LuchoTurtle remember the UX of the people we are talking about here ... 💭

**Comment by LuchoTurtle** [comment]
> @LuchoTurtle remember the UX of the people we are talking about here ... 💭 

That's true but I recall Tia A saying they'll be near the speaker, they just want their voices amped up. But you do bring up a fair point 😅

**Comment by nelsonic** [comment]
Order placed for the **`RODE INTERVIEW GO P/ WIRELESS GO`** ⌛ 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/194400/187188677-5bec322a-9c88-4d45-9c1b-3bd21cfc874f.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/194400/187188716-c6d4f3c0-552a-46e7-9d25-87a2fbb708e8.png">


Yes, it's just a "stick" to hold the microphone. 🙄 
But it improves the UX for the people using the mic. 🤞 
@iteles I've uploaded the comprovativo de pagamento and the factura to Google Drive:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/194400/187189066-4978d80c-fc1e-442d-81e3-672781136da1.png">
Will upload an actual "factura" if/when it's available.

**Comment by LuchoTurtle** [comment]
Awesome 🎉 . Although we should have tested if the wireless mic worked with the speaker before jumping into buying this. We can run the risk of none of this working at all :/. 

We'll see!

**Comment by iteles** [comment]
They've requested that the speaker and mic get tested on Wednesday and left there. Is that possible for you guys?

**Comment by nelsonic** [comment]
@iteles indeeeeed. that's what we're aiming for. 
The wireless mic will work fine with the B&O Beolit 20 speaker if it doesn't work with the LG. 
Honestly not at all worried. no risk. 
worst case scenario we order a whole PA system with express delivery and everything will be there on the day.

**Comment by nelsonic** [comment]
Rode Wireless Go Charging with the Interview Go (overpriced stick!) on the PC desk in the studio:
![EF02A2A6-CC06-4AA2-9931-D8B40EDC45AB](https://user-images.githubusercontent.com/194400/187413057-2b982645-3bee-4e83-ae93-7e030d5f8dc5.jpeg)

once both the RX and TX are fully charged I will test them out with our B&O Portable speaker. 🤞

**Comment by nelsonic** [comment]
@iteles and **`A*`** Tested the Microphone with me @home today and it worked well with the Beolit speaker:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/194400/187484757-63905370-c085-42da-a2e1-8e295f7f1abb.png">

Everything is fully charged and ready to go to Boamense:

![image](https://user-images.githubusercontent.com/194400/187485543-6b054028-b675-4c7f-acd5-f6b3e0acf869.png)

The single **`20W`** speaker proves the concept well. 👌 

@LuchoTurtle if you are able to bring your speakers for higher volume in the bigger room then please do on Saturday.

**Comment by nelsonic** [comment]
The microphone with the overpriced "stick" was a success at the event. it worked without any issues. 🎉 
Nobody said thank you for supplying the equipment. 👌 
Anyway ... closing. ✅

**Comment by iteles** [comment]
There were a Lot of thank you a when the equipment was dropped off. It worked well 👌🏻
