### ISSUE TITLE
Buy: HDMI Cable for 32" 40k 60Hz Samsung Standing Desk Monitor

### ISSUE THREAD

**Issue by nelsonic** [dwyl/studio#45]
This week @LuchoTurtle  was working at the Standing desk 🧑‍💻 
and noticed that the refresh rate on the [**`Samsung U32J59X`**]() was only **`30Hz`**: 👀 

https://www.samsung.com/us/computing/monitors/uhd-and-wqhd/32-uj590-uhd-monitor-lu32j590uqnxza/#specs

![samsung-monitor-spec](https://user-images.githubusercontent.com/194400/195968180-9140e0ef-4f1a-4b8a-8f3f-1a756bfe7274.png)

The max refresh available on Mac plugged directly to the HDMI is **`30Hz`**:

![samsung-display-max-30hz](https://user-images.githubusercontent.com/194400/195967673-13437d0d-903d-415c-9a68-b82e324f436c.png)

Through his research - now lost to the ether as it wasn't _captured_ ... - he noted that the **cable** used to _connect_  to the monitor dictates  the refresh rate ... i.e. _not_ all cables are made equal! lower spec ones can't handle the higher refresh rate!

# Todo:

+ [ ] order an **`HDMI @ 40k 60Hz`** cable ASAP to max the refresh of the monitor. 🛒 

@LuchoTurtle what conclusion did you reach on this? did you find a cable online for click-and-collect? 🤞

**Comment by LuchoTurtle** [comment]
@nelsonic I've looked and Worten and Radio Popular have these cables but at **three times the price** of the usual HDMI 2.1 cables. 

I'm going to buy [these](https://www.pcdiga.com/cabo-hdmi-2-1-ewent-ec1321-high-speed-c-ethernet-8k-1-8m-preto-ec1321?gclid=CjwKCAjwtKmaBhBMEiwAyINuwMfIOaO8TbnT4CgwhvPgCAYGvEy3Q22Z7ffeKucKLo7j_vQlbga7sRoCne0QAvD_BwE) here, they're much cheaper. I can drive there.

**Comment by LuchoTurtle** [comment]
Got two: one with 1.8m HDMI 2.1 for the TV (8K@60Hz, 4K@120Hz) and a 5m HDMI 2.0 for the monitor (4K@60Hz).

That's all they had 👍

**Comment by nelsonic** [comment]
5m? 😯
You sure it’s not a skipping rope? 🤷‍♂️ 😜

**Comment by nelsonic** [comment]
Remembered I had this adapter from ages ago:
![EA041C81-468E-402C-B4AE-A91547DE8211](https://user-images.githubusercontent.com/194400/195992321-b95bf6a6-4ed7-4158-9139-140f8077dd12.jpeg)

**Comment by nelsonic** [comment]
Getting **`60Hz`** on Mac: 

<img width="651" alt="60hz-display" src="https://user-images.githubusercontent.com/194400/195992479-ff7f7dc7-c9a3-46be-b676-e0deb441d216.png">

**Comment by nelsonic** [comment]
If the **`HDMI`** cable works, we'll use that. 👌

**Comment by nelsonic** [comment]
This is working. Closing. ✅
